### ISSUE TITLE
How is this compiled ?

### ISSUE THREAD

**Issue by Jm56Z** [TheOpenSpaceProgram/osp#1]
Just cloned the repository (and checked the license), and installed the glfw library.
I used the command:
`gcc src/main.cpp src/orbital/*.cpp src/render/renderlow/drawables/*.cpp src/render/renderlow/*.cpp src/util/*.cpp -Idep` from //osp/OSPGL

With this command, I get the following errors:

`the declaration of "shader* dbillboard::shader" changes the signification of "shader" from "class shader"`

`"wincolor_stdout_sink_mt" is not a member of "spdlog::sinks"`
`alternatives: "ansicolor_stdout_sink_mt"`

`no function corresponding to call "make_shared<<expression error> >()"`

Note that I (very) probably forgot something in my command, but perhaps a Makefile could be useful.

Have a great day, a KSP/OSP fan

**Comment by tatjam** [comment]
I will change the dangerous naming conventions! Using lower-case for all can't end well.

The spdlog errors are probably related to some windows stuff; output coloring requires some special handling on windows machines. Will probably simply remove spdlog coloring, it's not really required.

**Comment by Jm56Z** [comment]
I use snake_case naming, and if I have two names that are the same, I add an underscore to one of them, problem solved xD.

Also I forked, so if you don't want to bring unix support now you don't have to !

**Comment by tatjam** [comment]
Yeah, snake_case is the style of the C++ stdlib, but using it for classes feels clunky, not being able to name "shader" an instance of a class named "Shader" is annoying. Thanksfully Visual Studio made the renaming a 5 minute task :)

**Comment by Jm56Z** [comment]
Coding in windows... Pff... xD #linuxNerd
The problem was not the snake_case names here.
The error was a conflict between two names in your headers. (because std libs have extreme names)
You had a class named `shader` in `glad.h` and a part of a structure also named `shader` in `dbillboard.h` and g++ doesn't like that.

**Comment by tatjam** [comment]
Oh that's interesting, thought glad prefixed everything with gl... Well, anyway, CamelCase for classnames makes code more readable, which is a must!
